name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v3, which supports Node.js 20

      - name: Set up JDK 11
        uses: actions/setup-java@v4  # Updated to v3, which supports Node.js 20
        with:
          distribution: 'temurin'  # Specify the JDK distribution, e.g., 'temurin', 'zulu', 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku create your-app-name
          heroku deploy:jar target/*.jar --app your-app-name
