name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Updated to v3
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku create your-app-name
          heroku deploy:jar target/*.jar --app your-app-name
